export enum ClientEvents {
	connected = "connected",
	gameParams = "gameParams",
	update = "update",
	mode = "mode",
	move = "move",
	useSpell = "useSpell",
	stopWaiting = "stopWaiting",
	leave = "leave",
	gamePlay = "gamePlay",
	gameForfeit = "gameForfeit",
	gameInvite = "gameInvite",
	gameResponse = "gameResponse",
	checkGame = "checkGame",
};
export enum ServerEvents {
	started = "started",
	updated = "updated",
	finished = "finished",
	disconnect = "disconnect",
	waiting = "waiting",
	playing = "playing",
	gameReady = "gameReady",
	waitingForOpponent = "waitingForOpponent",
	disableNotifications = "disableNotifications",
	updateStatus = "updateStatus",
	gameInvite = "gameInvite",
	dataChanged = "dataChanged",
	gameResponse = "gameResponse",
};
export enum ChatEvents {
	/*Emit*/
	createChannel = "createChannel",
	updateChannel = "updateChannel",
	addUserToChannel = "addUserToChannel",
	setActiveChannel = "setActiveChannel",
	leaveChannel = "leaveChannel", 
	deleteChannel = "deleteChannel",
	joinChannel = "joinChannel",
	setAdmin = "setAdmin",
	kickUser = "kickUser",
	banUser = "banUser",
	resetActiveChannel = "resetActiveChannel",
	sendMessage = "sendMessage",
	/*reception*/
	receivedMessage = "receivedMessage",
	lastActiveChannel = "lastActiveChannel",
	userAdded = "userAdded",
	channelDeleted = "channelDeleted",
	newChannelCreated = "newChannelCreated",
	channelUpdated = "channelUpdated", 
	channelJoined = "channelJoined",
	kicked = "kicked",
	banned = "banned",

};